# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seqrecord',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
