# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 15:16
from __future__ import unicode_literals

from django.db import migrations
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alignment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignment',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False,
                                                         length=16, max_length=16, null=True),
        ),
    ]
