# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 15:18
from __future__ import unicode_literals

import uuid
from django.db import migrations


def gen_slug(apps, schema_editor):
    Alignment = apps.get_model('base', 'Alignment')
    for row in Alignment.objects.all():
        row.slug = str(uuid.uuid4()).replace('-', '')[:16]
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alignment_add_slug_field'),
    ]

    operations = [
        migrations.RunPython(gen_slug)
    ]
